config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'home' => 'pages#home', as: 'home'

  get ':id/questions/' => 'questions#quizzes', as: 'questions'

  match ':id/questions', to: 'questions#try_again', via: :delete, as:'try_again'


  resources :quizzes do
    resources :answers
  end

  resources :relationships

  

  

  
  #post 'questions/:id' => 'questions#quizzes', as: 'answers'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    include QuestionsHelper
    
    before_action :authenticate_user!

    def quizzes
        redirect_to home_path if validate_user current_user
        redirect_to home_path if (User.find(params[:id])).enrolling?(current_user.id)

        @quiz = Quiz.where(user_id: User.find(params[:id]))
        @quizzes = Quiz.all.where(user_id: User.find(params[:id]))
        @answers = Answer.all.where(user_id: current_user.id).where(quiz_id: @quiz)   
    end

    def try_again 
        current_user.answers.where(teacher_id: User.find(params[:id])).destroy_all
        redirect_to questions_path(User.find(params[:id]))
        flash[:notice] = "You may now try answering again"
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper

    def validate_user user
        
        if user.user_type == "Teacher"
            return true
        else
            return false
        end

    end


end

app/views/questions/_taken.html.erb
  <table class="table table-hover">
      <thead>
        <tr>
          <th>Questions</th>
          <th>Correct Answer</th>
          <th>Your Answer</th>
          <th>Result</th>
        </tr>
      </thead>
      
      <% for @a in @answers %>
      <tbody>
        <tr class="<%= @a.is_correct%>">
          <td><%= @a.quiz.question %></td>
          <td><%= @a.quiz.answer %></td>
          <td><%= @a.ans %></td>
          <td ><% if @a.is_correct %>
              Correct 
              <% else %> 
              Incorrect 
              <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>

  <div>
    <h4>Total Score: <b><%= current_user.answers.where(is_correct: true, teacher_id: User.find(params[:id])).count %></b> </h4>
  </div>

<br/>

<%= link_to "Try Again!", try_again_path(User.find(params[:id])), method: :delete, class: "btn btn-primary"  %>

app/views/questions/_untaken.html.erb
<% if current_user.enrolling?(User.find(params[:id])) %>
  <div class="col-md-6 col-md-offset-3">
    <div class="action-form">
      <center><h3>Quizzes from Teacher <%= User.find(params[:id]).first_name %></h3></center>
        <br/>
        <div class="form-actions">
          <% for @q in @quizzes %>
            <% if Answer.where(quiz_id: @q.id).where(user_id: current_user.id).count == 0  %>
              <%= form_for ([@q, @q.answers.build]) do |f| %>  
                <div class="field">
                    <%= f.label @q.question %></td>
                </div>
                  <br/>
                <div class="field">
                    <%= f.text_field :ans, placeholder: "Put your answer here" %></td>
                </div>
                  <br/>
                <div class="field">
                    <%= f.submit "Answer it!", class: "btn btn-primary" %></td>
                </div>  
              <% end %>
            <% end %>
          <% end %>
        <br/>
      </div>
    </div>
  </div>

<% else %>
  <h5><i>You have to enroll first</i></h5>

  <%= link_to "Back", home_path, class: "btn btn-primary" %>

<% end %>

app/views/questions/quizzes.html.erb
<% if current_user.answers.where(teacher_id: User.find(params[:id])).count < Quiz.where(user_id: User.find(params[:id])).count %>
  <%= render '/questions/untaken.html.erb' %>
<% else %>
  <%= render '/questions/taken.html.erb' %>
<% end %>