config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'home' => 'pages#home', as: 'home'

  get ':id/questions/' => 'questions#quizzes', as: 'questions'

  match ':id/questions', to: 'questions#try_again', via: :delete, as:'try_again'


  resources :quizzes do
    resources :answers
  end

  resources :relationships

  

  

  
  #post 'questions/:id' => 'questions#quizzes', as: 'answers'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_student.html.erb
<h1>Student</h2>
<table class="table table-hover">
      <thead>
        <tr>
          <th>Teacher's Name</th>
          <th>Status</th>
          <th>Your Score</th>
        </tr>
      </thead>
      <% for @u in @users %>
      <% if @u.quizzes.count > 0 %>
      <tbody>
        <tr>
        <td><%= @u.first_name %></td>
        <td>
          <% if current_user.answers.where(teacher_id: @u.id).count == Quiz.where(user_id: @u.id).count && Quiz.where(user_id: @u.id).count != 0  %>
          Completed!
          <% elsif current_user.answers.where(teacher_id: @u.id).count > 0 && current_user.answers.where(teacher_id: @u.id).count < Quiz.where(user_id: @u.id).count && Quiz.where(user_id: @u.id).count %>
            Incomplete
          <% else %>
            Unanswered
           <% end %>
        </td>
        <td>
        <% if current_user.answers.where(teacher_id: @u.id).count == Quiz.where(user_id: @u.id).count && @u.quizzes.count != 0  %>
          <%= current_user.answers.where(is_correct: true, teacher_id: @u.id).count %> / <%= @u.quizzes.count %>
        <% elsif current_user.answers.where(teacher_id: @u.id).count > 0 && current_user.answers.where(teacher_id: @u.id).count < Quiz.where(user_id: @u.id).count && Quiz.where(user_id: @u.id).count %>
          You have answered <%= current_user.answers.where(teacher_id: @u.id).count %> / <%= @u.quizzes.count %> quiz(zes)
        <% else %>
        There are <%= @u.quizzes.count %> quiz(zes)
        <% end %>
        </td>
        <td>
          <% unless current_user.enrolling?(@u) %>
					  <%= form_for(current_user.active_relationships.build) do |f| %>
						  <div><%= hidden_field_tag :enrolled_id, @u.id %></div>
						  <%= f.submit "Enroll", class: "btn btn-primary" %>
					  <% end %>
              <% else %>
              <%= link_to "Show", questions_path(@u.id), class: "btn btn-primary"%>
		      <% end %>
        </td>
        </tr>
      </tbody>
      <% end %>
    <% end %>
</table>

app/views/pages/_teacher.html.erb
<h1>Teacher</h1>

<h2>My Quizzes</h2> 
 
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>
      <% for @q in @quizzes %>
        <tbody>
          <tr>
          <td><%= @q.question %></td>
          <td><%= @q.answer %></td>
          <td><button type="button" class="btn btn-warning" data-toggle="modal" data-target="#<%= @q.id %>">Edit</button></td>
          <!-- Modal for Edit -->
            <div id=<%= @q.id %> class="modal fade" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Update Question</h4>
                  </div>
                  <div class="modal-body">
                    <%= form_for @q do |f| %>
                    <div class="field">
                    Question:
                        <%= f.text_field :question, required: true, autofocus: true %>    
                    </div>
                    <div class="field">
                    Correct Answer:
                        <%= f.text_field :answer, required: true %>    
                    </div>
                      <p><%= f.submit "Update Question", class: "btn btn-primary" %></p>
                    <% end %>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            <td><%= link_to "Delete", quiz_path(@q), method: :delete, data:{ confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
          </tr>
        </tbody>
      <% end %>
</table>
<!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-custom2" data-toggle="modal" data-target="#myModal">Add Question</button>
<!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
<!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Create Question</h4>
          </div>
          <div class="modal-body">
            <%= form_for @newQuiz do |f| %>
            <div class="field">
            Question:
                <%= f.text_field :question, required: true, autofocus: true %>    
            </div>
            <div class="field">
            Correct Answer:
                <%= f.text_field :answer, required: true %>    
            </div>
            <br/>
            <p><%= f.submit "Add Question", class: "btn btn-primary" %></p>
            
            <% end %>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

app/views/pages/home.html.erb
<% unless !user_signed_in? %>
<h1>Quiz Master Home</h1>
<% if current_user.user_type == "Teacher" %>
    <%= render '/pages/teacher.html.erb' %>
<% else %>
    <%= render '/pages/student.html.erb' %>
<% end %>
<% end %>

app/views/pages/index.html.erb
<style>

    body{
        background:linear-gradient(
            rgba(0,0,0,0.4),
            rgba(0,0,0,0.4)

        ), url("/bg2.jpg") no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    h1{
        color: black;
        font-weight: 500;
    }
    .footer-links{
        margin-top: 18%;
        text-align: center;
    }
    .container-index{
        opacity: 0.7;
        margin-left: 15%;
        margin-top: 5%;
    }
    .para{
        font-weight: 500;
        font-size: 110%;
    }
    
</style>


<div class="container-index">
            <h1>Welcome to Quiz Master</h1>
                <br/>
				<p class="para">
						Learning never stops! <br/>
						Keep on taking knowledge! <br/>
						Take your academics here at Quiz Master!
				</p>
</div>		
		
		
<p class="footer-links">About  Help  Blog  Status  Jobs  Terms  Privacy  Cookies  Ads  Info  Brand  Advertise  Business  Media  Developers  Directory  @ 2017  QuizMaster</p>
		